package at.gv.parlament.documentation.hermes.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;

public class SearchResultContentPage extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Accordion resultAccordion;
	@AutoGenerated
	private EmptyContentPage accordionPage2;
	@AutoGenerated
	private VideoContentPage accordionPage1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SearchResultContentPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// resultAccordion
		resultAccordion = buildResultAccordion();
		mainLayout.addComponent(resultAccordion);
		
		return mainLayout;
	}

	@AutoGenerated
	private Accordion buildResultAccordion() {
		// common part: create layout
		resultAccordion = new Accordion();
		resultAccordion.setImmediate(true);
		resultAccordion.setWidth("100.0%");
		resultAccordion.setHeight("100.0%");
		
		// accordionPage1
		accordionPage1 = new VideoContentPage();
		accordionPage1.setCaption("Content 1");
		accordionPage1.setImmediate(false);
		accordionPage1.setWidth("-1px");
		accordionPage1.setHeight("100.0%");
		resultAccordion.addTab(accordionPage1, "Tab", null);
		
		// accordionPage2
		accordionPage2 = new EmptyContentPage();
		accordionPage2.setCaption("Content 2");
		accordionPage2.setImmediate(false);
		accordionPage2.setWidth("-1px");
		accordionPage2.setHeight("100.0%");
		resultAccordion.addTab(accordionPage2, "Content 1", null);
		
		return resultAccordion;
	}

}
