package at.gv.parlament.documentation.hermes.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ExternalResource;
import com.vaadin.spring.annotation.SpringComponent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Video;

@SpringComponent
public class VideoPage extends CustomComponent implements IVideoPage {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private VerticalLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VideoPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		Video v = new Video( "video" ); // Instantiate video player widget.
		// Specify a list of your video in one or more formats.
		// Different browsers support various different video formats.
		v.setSources( 
		    new ExternalResource( "http://www.ntsretail.com/web_files/cms_daten/131210_ntswincash_720p.mp4" )
		); 
		v.setWidth( "640px" ); // Set size of the video player's display area on-screen.
		v.setHeight( "360px" );
		mainLayout.addComponent(v);
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new VerticalLayout();
	}

}
