package at.gv.parlament.documentation.hermes.view.main;

import org.springframework.beans.factory.annotation.Autowired;

import at.gv.parlament.documentation.hermes.controller.main.IMainViewController;
import at.gv.parlament.documentation.hermes.controller.main.MenuAction;
import at.gv.parlament.documentation.hermes.view.AbstractHermesApplicationView;
import at.gv.parlament.documentation.hermes.view.EmptyPage;
import at.gv.parlament.documentation.hermes.view.IContentPage;

import com.vaadin.navigator.View;
import com.vaadin.spring.navigator.annotation.SpringView;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

@SpringView(MainView.NAME)
public class MainView extends AbstractHermesApplicationView implements IMainView, View {

	private static final long serialVersionUID = 1L;
	public static final String NAME = "";
	private VerticalLayout mainLayout;
	private Panel contentPanel;
	@SuppressWarnings("unused")
	private AbsoluteLayout contentPanelLayout;
	private MenuBar menuBar;
	
	private IMainViewController controller;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainView() {
		buildMainLayout();
	}
	
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// menuBar
		menuBar = new MenuBar();
		menuBar.setImmediate(false);
		menuBar.setWidth("-1px");
		menuBar.setHeight("50px");
		mainLayout.addComponent(menuBar);
		
		contentPanel = new Panel();
		contentPanel.setSizeFull();
		mainLayout.addComponent(contentPanel);
		contentPanel.setContent(new EmptyPage());
		
		mainLayout.setExpandRatio(menuBar, 0);
		mainLayout.setExpandRatio(contentPanel, 1);
		setCompositionRoot(mainLayout);
		return mainLayout;
	}

	@Override
	public void setContentPage(IContentPage view) {
		contentPanel.setContent(view);
		view.onDisplayPage();
	}

	@Override
	public void addMenuEntry(String caption, MenuAction action) {
		menuBar.addItem(caption, new MenuBar.Command() {
			/**
			 * 
			 */
			private static final long serialVersionUID = 5040516096922544186L;

			@Override
			public void menuSelected(MenuItem selectedItem) {
				controller.menuSelect(action);
			}
		});
	}

	@Autowired
	@Override
	public void setController(IMainViewController controller) {
		this.controller = controller;
		this.controller.setMainView(this);
	}
	
}
