package at.gv.parlament.hermes;

import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class MainPage extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VerticalLayout mainLayout;
	private Panel contentPanel;
	@SuppressWarnings("unused")
	private AbsoluteLayout contentPanelLayout;
	private MenuBar menuBar;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// menuBar
		menuBar = new MenuBar();
		menuBar.setImmediate(false);
		menuBar.setWidth("-1px");
		menuBar.setHeight("50px");
		mainLayout.addComponent(menuBar);
		
		contentPanel = new Panel();
		contentPanel.setSizeFull();
		mainLayout.addComponent(contentPanel);
		contentPanel.setContent(new EmptyContentPage());
		
		mainLayout.setExpandRatio(menuBar, 0);
		mainLayout.setExpandRatio(contentPanel, 1.0f);
		
		return mainLayout;
	}
	
	public void addMenuEntry(final String title, final Component contentPage) {
		menuBar.addItem(title, new MenuBar.Command() {
		
			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			@Override
			public void menuSelected(MenuItem selectedItem) {
				contentPanel.setContent(contentPage);
				contentPanel.setSizeFull();
			}
		});
	}

}
