package at.gv.parlament.hermes;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Tree;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class SearchContentPage extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalSplitPanel splitterPanel;
	@AutoGenerated
	private Panel resultContentPanel;
	@AutoGenerated
	private VerticalLayout resultVerticalLayout;
	@AutoGenerated
	private EmptyContentPage emptyContentPage_2;
	@AutoGenerated
	private Tree resultTree;
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public SearchContentPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		
		setResultContent(new SearchResultContentPage());
				
	}

	public void setSearchResultComponent(final Component contentPage) {
	}

	public void setResultContent(Component searchResultContentPage) {
		resultContentPanel.setContent(searchResultContentPage);
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// splitterPanel
		splitterPanel = buildSplitterPanel();
		mainLayout.addComponent(splitterPanel);
		mainLayout.setExpandRatio(splitterPanel, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildSplitterPanel() {
		// common part: create layout
		splitterPanel = new HorizontalSplitPanel();
		splitterPanel.setImmediate(false);
		splitterPanel.setWidth("100.0%");
		splitterPanel.setHeight("100.0%");
		
		// resultTree
		resultTree = new Tree();
		resultTree.setImmediate(false);
		resultTree.setWidth("-1px");
		resultTree.setHeight("100.0%");
		splitterPanel.addComponent(resultTree);
		
		// resultContentPanel
		resultContentPanel = buildResultContentPanel();
		splitterPanel.addComponent(resultContentPanel);
		
		return splitterPanel;
	}

	@AutoGenerated
	private Panel buildResultContentPanel() {
		// common part: create layout
		resultContentPanel = new Panel();
		resultContentPanel.setImmediate(false);
		resultContentPanel.setWidth("100.0%");
		resultContentPanel.setHeight("100.0%");
		
		// resultVerticalLayout
		resultVerticalLayout = buildResultVerticalLayout();
		resultContentPanel.setContent(resultVerticalLayout);
		
		return resultContentPanel;
	}

	@AutoGenerated
	private VerticalLayout buildResultVerticalLayout() {
		// common part: create layout
		resultVerticalLayout = new VerticalLayout();
		resultVerticalLayout.setImmediate(false);
		resultVerticalLayout.setWidth("100.0%");
		resultVerticalLayout.setHeight("-1px");
		resultVerticalLayout.setMargin(false);
		
		// emptyContentPage_2
		emptyContentPage_2 = new EmptyContentPage();
		emptyContentPage_2.setImmediate(false);
		emptyContentPage_2.setWidth("-1px");
		emptyContentPage_2.setHeight("-1px");
		resultVerticalLayout.addComponent(emptyContentPage_2);
		
		return resultVerticalLayout;
	}
}
