-- MySQL Script generated by MySQL Workbench
-- Thu Jan 29 22:50:00 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hermesdb
-- -----------------------------------------------------
-- This database is used for Hermes media tool.
DROP SCHEMA IF EXISTS `hermesdb` ;

-- -----------------------------------------------------
-- Schema hermesdb
--
-- This database is used for Hermes media tool.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hermesdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hermesdb` ;

-- -----------------------------------------------------
-- Table `hermesdb`.`filestorage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hermesdb`.`filestorage` ;

CREATE TABLE IF NOT EXISTS `hermesdb`.`filestorage` (
  `id` INT NOT NULL,
  `filepath` VARCHAR(2000) NOT NULL,
  `hashvalue` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `filestorage1_UNIQUE` ON `hermesdb`.`filestorage` (`filepath` ASC, `hashvalue` ASC);


-- -----------------------------------------------------
-- Table `hermesdb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hermesdb`.`category` ;

CREATE TABLE IF NOT EXISTS `hermesdb`.`category` (
  `id` INT NOT NULL,
  `no` VARCHAR(45) NOT NULL,
  `name` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `hermesdb`.`video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hermesdb`.`video` ;

CREATE TABLE IF NOT EXISTS `hermesdb`.`video` (
  `id` INT NOT NULL,
  `name` VARCHAR(254) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `filestorageid` INT NOT NULL,
  `categoryid` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_video_filestorage`
    FOREIGN KEY (`filestorageid`)
    REFERENCES `hermesdb`.`filestorage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_category1`
    FOREIGN KEY (`categoryid`)
    REFERENCES `hermesdb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_video_filestorage_idx` ON `hermesdb`.`video` (`filestorageid` ASC);

CREATE INDEX `fk_video_category1_idx` ON `hermesdb`.`video` (`categoryid` ASC);

SET SQL_MODE = '';
GRANT USAGE ON *.* TO hermes_admin;
 DROP USER hermes_admin;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'hermes_admin' IDENTIFIED BY 'herminator';

GRANT ALL ON `hermesdb`.* TO 'hermes_admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
